### ISSUE TITLE
Establish project governance, use good practices.

### ISSUE THREAD

**Issue by halcyondude** [cncf/landscape-graph#47]

**Comment by rohankmr414** [comment]
we can add checks for semantic PRs.
https://github.com/zeke/semantic-pull-requests

**Comment by halcyondude** [comment]
Useful guidance:

https://youtu.be/430XXSbUgeQ

**Comment by halcyondude** [comment]
> we can add checks for semantic PRs.
> 
> https://github.com/zeke/semantic-pull-requests

This is a great idea @rohankmr414 !

Please do create an issue and/or a PR!

**Comment by rohankmr414** [comment]
we should require contributors to sign off their commits as well
https://github.com/apps/dco

**Comment by halcyondude** [comment]
re-opening, automation closed it.  the checks for PR formatting are in.

the scope of this issue is quite a big broader however.

**Comment by halcyondude** [comment]
TAG Contributor Strategy created this: https://github.com/cncf/project-template
